---
- name: Include users vars
  include_vars: ../vars/controller_users.yml
  tags:
    - users
    - alltags

- import_role:
    name: infra.controller_configuration.users
  tags:
    - users
    - alltags
...
