---
- name: Include credentials vars
  include_vars: ../vars/controller_credentials.yml
  tags:
    - credentials
    - alltags

- import_role:
    name: infra.controller_configuration.credentials
  tags:
    - credentials
    - alltags
...
