---
- name: Include credential types vars
  include_vars: ../vars/controller_credential_types.yml
  tags:
    - credtypes
    - alltags

- import_role:
    name: infra.controller_configuration.credential_types
  tags:
    - credtypes
    - alltags
...
