---
- name: Include groups vars
  include_vars: ../vars/controller_groups.yml
  tags:
    - groups
    - alltags

- import_role:
    name: infra.controller_configuration.groups
  tags:
    - groups
    - alltags
...
