kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-github-runner-tower
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- github-ssulliva-tower-config
