---
workflows:
- name: Complicated Schema Workflow
  description: Complicated Schema Workflow
  organization: Default
  schema:
  - identifier: Node101
    unified_job_template: workflow_test_template
    inventory: Demo Inventory
    extra_data:
      name: John
    scm_branch: master
    job_type: run
    job_tags: jobtag1, jobtag2
    skip_tags: jobtag3
    limit: a:b
    diff_mode: 'false'
    verbosity: 1
    all_parents_must_converge: 'false'
    state: present
    credentials:
    - Demo Credential
    success_nodes:
    - Node201
    - Node301
    failure_nodes:
    - Node603
  - identifier: Node201
    unified_job_template: No Survey Template no vars
    success_nodes:
      - Node301
  - identifier: Node301
    unified_job_template: No Survey Template no vars
    success_nodes:
    - Node401
  - identifier: Node401
    unified_job_template: workflow_test_template
    inventory: Demo Inventory
    extra_data:
      name: John
    scm_branch: master
    job_type: run
    job_tags: jobtag1, jobtag2
    skip_tags: jobtag3
    limit: a:b
    diff_mode: 'false'
    verbosity: 1
    all_parents_must_converge: 'true'
    state: present
    credentials:
    - Demo Credential
    success_nodes:
    - Node501
    failure_nodes:
    - Node502
  - identifier: Node501
    unified_job_template: No Survey Template no vars
    success_nodes:
    - Node601
    - Node602
    failure_nodes:
    - Node603
  - identifier: Node502
    unified_job_template: No Survey Template no vars
    success_nodes:
    - Node604
  - identifier: Node601
    unified_job_template: No Survey Template no vars
  - identifier: Node602
    unified_job_template: No Survey Template no vars
  - identifier: Node603
    unified_job_template: No Survey Template no vars
    all_parents_must_converge: 'true'
    success_nodes:
    - Node701
  - identifier: Node604
    unified_job_template: No Survey Template no vars
  - identifier: Node701
    unified_job_template: No Survey Template no vars
  survey_enabled: true
  survey: "{{ lookup('template', 'template_surveys/basic_survey.json') | regex_replace('\\n',
    '') }}"
  extra_vars: "{{ survey_extra_vars }}"
