---

- name: Import vars
  include_vars:
    file: "vars/extra_vars.yaml"
  tags:
    - always

- name: Add organizations
  include_tasks: "tasks/add_organizations.yaml"
  args:
    apply:
      tags:
      - organizations
  tags:
    - organizations

- name: Add credential types
  include_tasks: "tasks/add_credential_types.yaml"
  args:
    apply:
      tags:
      - credential_types
  tags:
    - credential_types    

- name: Add credentials
  include_tasks: "tasks/add_credentials.yaml"
  args:
    apply:
      tags:
      - credentials
  tags:
    - credentials 

- name: Add projects
  include_tasks: "tasks/add_projects.yaml"
  args:
    apply:
      tags:
      - projects
  tags:
    - projects

- name: Add templates
  include_tasks: "tasks/add_templates.yaml"
  args:
    apply:
      tags:
      - templates
  tags:
    - templates

- name: Add workflows
  include_tasks: "tasks/add_workflows.yaml"
  args:
    apply:
      tags:
      - workflows
  tags:
    - workflows    
