---
- name: Playbook to configure ansible tower post installation
  hosts: localhost
  connection: local
  # Define following vars here, or in tower_configs/tower_auth.yml
  # tower_hostname: ansible-tower-web-svc-test-project.example.com
  # tower_username: admin
  # tower_password: changeme
  pre_tasks:
    - name: Include vars from tower_configs directory
      include_vars:
        dir: ./tower_configs
        ignore_files: [tower_config.yml.template]
        extensions: ["yml"]
  roles:
    - {role: tower_settings, when: tower_settings is defined}
    - {role: organizations, when: tower_organizations is defined}
    - {role: users, when: tower_user_accounts is defined}
    - {role: teams, when: tower_teams is defined}
    - {role: credentials, when: tower_credentials is defined}
    - {role: inventories, when: tower_inventories is defined}
    - {role: projects, when: tower_projects is defined}
    - {role: inventory_sources, when: tower_inventory_sources is defined}
    - {role: hosts, when: tower_hosts is defined}
    - {role: job_templates, when: tower_templates is defined}
    - {role: workflow_job_templates, when: workflow_job_templates is defined}
    - {role: schedules, when: tower_schedules is defined}
    - {role: notifications, when: tower_notifications is defined}
    - {role: tower_role, when: tower_rbac is defined}
