---
- name: Import JSON
  include_vars:
    file: "json/templates.json"
    name: templates_json

- name: Add Templates
  include_role:
    name: job_templates
  vars:
    tower_templates: "{{ templates_json.templates }}"
