---
- name: Import JSON
  include_vars:
    file: "json/projects.json"
    name: projects_json

- name: Add projects
  include_role:
    name: projects
  vars:
    tower_projects: "{{ projects_json.projects }}"
