---
- name: Import vars
  include_vars:
    file: "vars/extra_vars.yml"

- name: Import JSON
  include_vars:
    file: "json/workflows_new.json"
    name: workflows_json

- name: Add Templates
  include_role:
    name: workflow_job_templates
  vars:
    tower_workflows: "{{ workflows_json.workflows }}"
    tower_password: "{{ tower_passname | default(omit) }}"
