---
tower_server: ""
tower_oauthtoken: ""
tower_validate_certs: false
tower_genie_rbac_secure_logging: "{{tower_genie_secure_logging | default(False)}}"

tower_rbac:
  - user: jdoe
    target_team: "My Team"
    role: member
  - team: "My Team"
    organization: "Default"
    role: execute
