---
- name: "Create the output directory: {{ output_path }}"
  ansible.builtin.file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current roles to the output yaml file"
  ansible.builtin.template:
    src: "templates/current_roles.j2"
    dest: "{{ __dest }}"
    mode: '0644'
  vars:
    main_object_type: "{{ object_type }}"
    __dest: "{{ output_path }}/current_roles_{{ current_user_roles.key | regex_replace('/', '_') }}.yaml"
  loop: "{{ current_asset_value | dict2items }}"
  loop_control:
    loop_var: current_user_roles
    label: "{{ current_user_roles.key }} at file {{ __dest }}"
...
