---

  - name: Create Ansible Tower inventory 
    tower_inventory:
      name: "{{ tower_inv_name }}"
      description: "{{ tower_inv_src_desc }}"
      organization: "{{ tower_org }}"
      state: "present"

  - name: Add an inventory source
    tower_inventory_source:
      name: "{{ tower_inv_src_name }}"
      source: "{{ tower_inv_src }}"
      description: "{{ tower_inv_src_description }}"
      inventory: "{{ tower_inv_name }}"
      credential: "{{ tower_inv_credential }}"
      overwrite: True
      update_on_launch: True