---
- name: update web servers
  hosts: localhost
  remote_user: root
  vars:
    tower_validate_certs: false
  collections:
    - ansible.tower
    - redhat_cop.tower_configuration

  pre_tasks:
    - name: Include vars from tower_configs directory
      include_vars:
        dir: ./tower_configs
        ignore_files: [tower_config.yml.template]
        extensions: ["yml"]
      tags:
        - always

  tasks:
    - debug:
        var: playbook_dir
    - debug:
        var: ansible_config_file