---
name: Merge Bot

on:
  pull_request:
    types:
      - labeled

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Merge changelog automated PR
      uses: squalrus/merge-bot@v0.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        labels: changelog, automated pr
