name: Run Test Playbooks AWX

on: [push, pull_request]

jobs:
  Integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: "Build AWX stack"
        run: cd .github/awxcompose && docker-compose up -d

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '60s'

      - name: "Wait for awx to be alive"
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost/api/v2/ping'
          responseCode: 200
          timeout: 600000  # Wait max 10 mins for response
          interval: 3000

      - name: "Install Galaxy dependencies"
        run: ansible-galaxy collection install -r .github/collections/requirements.yml

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '20s'

      - name: Update CA trust in awx_web container
        run: docker exec awx_web '/usr/bin/update-ca-trust'

      - name: Update CA trust in awx_task container
        run: docker exec awx_task '/usr/bin/update-ca-trust'

      - name: Test Internet
        run: cd .github/awxcompose && docker-compose down && docker-compose up

      - name: Test Internet
        run: docker exec awx_task ping -c 4 google.com

      - name: Test Internet
        run: docker exec awx_task wget https://github.com/ansible/

      - name: "Perform playbook tests"
        run: ansible-playbook playbooks/configure_tower.yml -e tower_hostname=http://localhost -e tower_username=admin -e tower_password=password -vvv

      - name: "Perform export model playbook tests"
        run: ansible-playbook playbooks/configure_tower_export_model.yml -e tower_hostname=http://localhost -e tower_username=admin -e tower_password=password
