name: Run Test Playbooks

on: [push, pull_request]

jobs:
  Integration-test:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: Login to RedHat registry
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.RegistryUsername }}
          DOCKER_PASSWRD: ${{ secrets.RegistryPassword }}
        run: |
          docker login registry.redhat.io -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      - name: "Build AWX stack"
        run: cd .docker && docker-compose up -d

      - name: "Wait for awx to be alive"
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost/api/v2/ping'
          responseCode: 200
          timeout: 600000  # Wait max 10 mins for response
          interval: 3000

      - name: "Install Galaxy dependencies"
        run: ansible-galaxy collection install -r .github/collections/requirements.yml

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '20s'

      - name: "Perform playbook tests"
        run: ansible-playbook playbooks/configure_tower.yml -e tower_hostname=http://localhost -e tower_username=admin -e tower_password=password

      - name: "Perform export model playbook tests"
        run: ansible-playbook playbooks/configure_tower_export_model.yml -e tower_hostname=http://localhost -e tower_username=admin -e tower_password=password
