name: Run Test Playbooks

on: [push, pull_request]

jobs:
  Integration-test:

    runs-on: ubuntu-latest

    # services:
    #   rabbitmq:
    #     image: ansible/awx_rabbitmq:3.7.4
    #     options: >- 
    #       --name awx_rabbitmq
    #       --hostname=awx_rabbitmq
    #     env:
    #       RABBITMQ_DEFAULT_VHOST: "awx"
    #       RABBITMQ_DEFAULT_USER: "guest"
    #       RABBITMQ_DEFAULT_PASS: "guest"
    #       RABBITMQ_ERLANG_COOKIE: cookiemonster

    #   memcached:
    #     image: memcached:alpine
    #     options: >-
    #       --name awx_memcached
    #       --hostname=awx_memcached

    #   postgres:
    #     image: postgres:10
    #     ports:
    #     - 5432:5432
    #     options: >-
    #       --name awx_postgres
    #       --hostname=awx_postgres
    #       --volume=src:dest
    #     env:
    #       POSTGRES_USER: awx
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: awx
    #       PGDATA: /var/lib/postgresql/data/pgdata

    #   awx_web:
    #     image: registry.redhat.io/ansible-tower-36/ansible-tower
    #     options: >- 
    #       --name=awx_web 
    #       --user=root 
    #       --volume=host-src:container-dest 
    #       --hostname=awx_web
    #     ports:
    #     - 80:8052

    #   awx_task:
    #     image: registry.redhat.io/ansible-tower-36/ansible-tower
    #     options: >- 
    #       --name=awx_task
    #       --user=root 
    #       --volume=host-src:container-dest 
    #       --hostname=awx_task
    #       --command=/usr/bin/launch_awx_task.sh

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      -
        name: Login to RedHat Registry
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RegistryUsername }}
          password: ${{ secrets.RegistryPassword }}

      - name: "Build AWX stack"
        run: cd .docker && docker-compose up -d

      - name: List containers
        run: docker ps -a

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '60s'

      - name: check port 80
        run: curl http://localhost:80

      - name: "Wait for awx to be alive"
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost/api/v2/ping'
          responseCode: 200
          timeout: 600000  # Wait max 10 mins for response
          interval: 3000

      - name: "Install Galaxy dependencies"
        run: ansible-galaxy collection install -r .github/collections/requirements.yml

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '20s'

      - name: "Perform playbook tests"
        run: ansible-playbook playbooks/configure_tower.yml -e tower_hostname=http://localhost -e tower_username=admin -e tower_password=password

      - name: "Perform export model playbook tests"
        run: ansible-playbook playbooks/configure_tower_export_model.yml -e tower_hostname=http://localhost -e tower_username=admin -e tower_password=password
